version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true # fail on all warnings to avoid broken references
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docsbuild
submodules:
  include:
    - "docs/tutorials/notebooks"
  recursive: true
